---
- name: Setup for Ubuntu
  tags: opendkim
  include_tasks: "setup_ubuntu.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Setup for EL (RHEL/CentOS/Rocky/Alma)
  tags: opendkim
  include_tasks: "setup_el.yml"
  when: ansible_os_family == 'RedHat'

- name: Opendkim directory
  tags: opendkim
  file:
    path: /etc/opendkim
    state: directory

- name: Opendkim keys directory
  tags: opendkim
  file:
    path: /etc/opendkim/keys
    state: directory

- name: Opendkim TrustedHosts configuration
  tags: opendkim
  copy:
    src: TrustedHosts
    dest: /etc/opendkim/TrustedHosts
  notify:
    - restart opendkim

- name: Opendkim configuration
  tags: opendkim
  template:
    src: opendkim.conf.j2
    dest: /etc/opendkim.conf
  notify:
    - restart opendkim

- name: Opendkim KeyTable configuration
  tags: opendkim
  template:
    src: KeyTable.j2
    dest: /etc/opendkim/KeyTable
  notify:
    - restart opendkim

- name: Opendkim SigningTable configuration
  tags: opendkim
  template:
    src: SigningTable.j2
    dest: /etc/opendkim/SigningTable
  notify:
    - restart opendkim

- name: Generate default signing key
  tags: opendkim
  command: "{{ opendkim_opendkim_genkey_path }} -s {{ dkim_selector }} -d {{ dkim_domains[0] }} -D /etc/opendkim/keys"
  args:
    creates: "/etc/opendkim/keys/{{ dkim_selector }}.private"
  changed_when: false
  notify:
    - restart opendkim
  when: not opendkim_one_key_per_domain

- name: Opendkim default signing key file ownership
  tags: opendkim
  file:
    path: "/etc/opendkim/keys/{{ dkim_selector }}.private"
    owner: opendkim
    group: opendkim
    mode: '0600'
  when: not opendkim_one_key_per_domain

- name: Ensure per-domain key directories exist
  tags: opendkim
  file:
    path: "/etc/opendkim/keys/{{ item }}"
    state: directory
    owner: opendkim
    group: opendkim
    mode: '0750'
  loop: "{{ dkim_domains }}"
  when: opendkim_one_key_per_domain

- name: Generate per-domain signing keys
  tags: opendkim
  command: "{{ opendkim_opendkim_genkey_path }} -s {{ dkim_selector }} -d {{ item }} -D /etc/opendkim/keys/{{ item }}"
  args:
    creates: "/etc/opendkim/keys/{{ item }}/{{ dkim_selector }}.private"
  changed_when: false
  loop: "{{ dkim_domains }}"
  notify:
    - restart opendkim
  when: opendkim_one_key_per_domain

- name: Ensure per-domain private key ownership
  tags: opendkim
  file:
    path: "/etc/opendkim/keys/{{ item }}/{{ dkim_selector }}.private"
    owner: opendkim
    group: opendkim
    mode: '0600'
  loop: "{{ dkim_domains }}"
  when: opendkim_one_key_per_domain

- name: Start and enable Opendkim
  tags: opendkim
  systemd:
    name: opendkim
    state: started
    enabled: true
